CREATE TABLE IF NOT EXISTS orders (
  id         BIGINT AUTO_INCREMENT PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  amount     DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  status     VARCHAR(50) NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
