package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/fpessoa64/desafio03_clean_arch/graph/model"
	"github.com/fpessoa64/desafio03_clean_arch/internal/entity"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*entity.Order, error) {
	o := &entity.Order{
		Name:   input.Name,
		Amount: input.Amount,
		Status: input.Status,
	}
	if err := r.Resolver.UC.Create(ctx, o); err != nil {
		return nil, err
	}
	return o, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *orderResolver) CreatedAt(ctx context.Context, obj *entity.Order) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*entity.Order, error) {
	orders, err := r.Resolver.UC.List(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*entity.Order, len(orders))
	for i := range orders {
		result[i] = &orders[i]
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
