// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	Name   string  `json:"name"`
	Amount float64 `json:"amount"`
	Status string  `json:"status"`
}

type Mutation struct {
}

type Query struct {
}
